M48
; DRILL file {KiCad 8.0.7-1.fc41} date 2025-01-19T14:37:27-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-19T14:37:27-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-1.fc41
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X151.275Y-141.75
T2
X130.275Y-141.75
M30
